language: java
dist: trusty
sudo: false   # Linux OS: run in container


before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install: true